// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blazor_crud.Data;

#nullable disable

namespace blazor_crud.Data.Migrations
{
    [DbContext(typeof(CrudDbContext))]
    [Migration("20220310180822_PrimeraMigracion")]
    partial class PrimeraMigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("blazor_crud.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chasis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chasis = "Chasis 1",
                            Color = "Color 1",
                            Comentario = "Comentario 1",
                            Foto = "Foto 1",
                            Marca = "Marca 1",
                            Modelo = "Modelo 1",
                            Year = "Year 1"
                        },
                        new
                        {
                            Id = 2,
                            Chasis = "Chasis 2",
                            Color = "Color 2",
                            Comentario = "Comentario 2",
                            Foto = "Foto 2",
                            Marca = "Marca 2",
                            Modelo = "Modelo 2",
                            Year = "Year 2"
                        },
                        new
                        {
                            Id = 3,
                            Chasis = "Chasis 3",
                            Color = "Color 3",
                            Comentario = "Comentario 3",
                            Foto = "Foto 3",
                            Marca = "Marca 3",
                            Modelo = "Modelo 3",
                            Year = "Year 3"
                        },
                        new
                        {
                            Id = 4,
                            Chasis = "Chasis 4",
                            Color = "Color 4",
                            Comentario = "Comentario 4",
                            Foto = "Foto 4",
                            Marca = "Marca 4",
                            Modelo = "Modelo 4",
                            Year = "Year 4"
                        },
                        new
                        {
                            Id = 5,
                            Chasis = "Chasis 5",
                            Color = "Color 5",
                            Comentario = "Comentario 5",
                            Foto = "Foto 5",
                            Marca = "Marca 5",
                            Modelo = "Modelo 5",
                            Year = "Year 5"
                        },
                        new
                        {
                            Id = 6,
                            Chasis = "Chasis 6",
                            Color = "Color 6",
                            Comentario = "Comentario 6",
                            Foto = "Foto 6",
                            Marca = "Marca 6",
                            Modelo = "Modelo 6",
                            Year = "Year 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
